apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: local-storage
  volumeName: local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi