apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      name: petclinic-app
  template:
    metadata:
      labels:
        name: petclinic-app
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: africkinbear/petclinic:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: petclinic-secrets
                  key: MYSQL_PASS
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: petclinic-secrets
                  key: MYSQL_URL
            - name: SPRING_PROFILES_ACTIVE
              value: mysql