apiVersion: v1
kind: Secret
metadata: 
  name: petclinic-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: admin123
  MYSQL_USER: petclinic
  MYSQL_PASS: petclinic
  MYSQL_URL: jdbc:mysql://mysql-uat.default.svc.cluster.local:3306/petclinic
  MYSQL_DATABASE: petclinic